## Mybatis
mybatis-plus:
  global-config:
    refresh: true
    sql-parser-cache: false
  configuration:
    cache-enabled: false

## Druid
user:
  druid:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stereo-dev?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: ivanna83
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    filters: stat,wall,log4j
    validationQuery: SELECT 'X' FROM dual
    validationQueryTimeout: 3
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandonedTimeoutMillis: 20000
    removeAbandoned: true
    logAbandoned: true
    logDifferentThread: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
    useGlobalDataSourceStat: true
    druidRegistrationUrl: /druid/*
    resetEnable: true
    ##loginUsername = "admin":
    ##loginPassword = "1234567890":
    filtersUrlPatterns: /*
    exclusions: "*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*"
    sessionStatMaxCount: 2000
    sessionStatEnable: true
    principalSessionName: session_user_key
    profileEnable: true

## log
logging:
  config: service-auth/src/main/resources/log4j-dev.properties
